### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by lbusoni** [astro-tiptop/TIPTOP#1]
Ciao Fabio,
I tried to run the command line example for the command line on my laptop:

`./tiptopCLT.py localTest/params1GPU MASTSEL/data/windpsd_mavis.fits localTest/test`

It fails on module fourier

```
Traceback (most recent call last):
  File "./tiptopCLT.py", line 6, in <module>
    from tiptop import *
  File "/Users/lbusoni/git/TIPTOP/tiptop.py", line 3, in <module>
    from fourierPSF.fourierModel import *
  File "/Users/lbusoni/git/TIPTOP/fourierPSF/fourierModel.py", line 33, in <module>
    import fourier.FourierUtils as FourierUtils
ModuleNotFoundError: No module named 'fourier'
```

but I guess it will fail also on the module aoSystem soon afterward

Is there a setup procedures, or list of dependencies/requirements?

**Comment by FabioRossiArcetri** [comment]
Ciao Lorenzo,

  if you look at the code of 
TIPTOP/fourierPSF/fourierModel.py
line 33 is:
import FourierUtils
so the problem does not occur.
Consider that TIPTOP is using submodules and that the current version of is:
75af070

You can try to update your local copy, if the problem persists let me know.

Ciao
Fabio

**Comment by lbusoni** [comment]
Apparently the command in README to clone the repo

`git clone --recurse-submodules --remote-submodules https://github.com/FabioRossiArcetri/TIPTOP.git
`

clones an old version of fourierPSF.

It looks like after the clone you have to use
 
`git submodule update --recursive `

to update to the current version of submodules.

I'm not familiar with submodules though, so there may be a better way. 

Anyhow, the problem is still there, as import FourierUtils still fails.

**Comment by FabioRossiArcetri** [comment]
Until a better solution is put into place, for now adding the modules folders to you PATH and PYTHONPATH should work. Something like this in your .bashrc

export PYTHONPATH="${PYTHONPATH}:/home/frossi/dev:/home/frossi/dev/SEEING:/home/frossi/dev/SYMAO:/home/frossi/dev/MASTSEL:/home/frossi/dev/fourierPSF:/home/frossi/corsoPython:/home/frossi/dev/P3"
export PATH="${PATH}:/home/frossi/dev:/home/frossi/dev/SEEING:/home/frossi/dev/SYMAO:/home/frossi/dev/MASTSEL:/home/frossi/dev/fourierPSF:/home/frossi/dev/P3"

**Comment by Teusia** [comment]
@lbusoni did you try again with the new method of instalation?

**Comment by saimn** [comment]
Installation of TIPTOP and dependencies should be much easier now: `pip install astro-tiptop` (https://tiptop.readthedocs.io/en/main/usage.html#installation).
