### ISSUE TITLE
Automatic install on main branch not working

### ISSUE THREAD

**Issue by Teusia** [astro-tiptop/TIPTOP#13]
Hello,

I think this is more directed toward @guidoagapito , if users download the main branch and try to install using pip install -e . from their local copy they have to manually install the third party libraries of P3, MASTSEL, SEEING and SYMAO as described in the readme. How ever I remember that @guidoagapito had made it such that this by hand installation was no longer necessary. Could you find out what made it work before?
Else tell me and I'll try to figure this out myself.

Cheers,
Anne-Laure C

**Comment by saimn** [comment]
Installation will now install dependencies, so closing.
