### ISSUE TITLE
Draft installation manual

### ISSUE THREAD

**Issue by Teusia** [astro-tiptop/TIPTOP#2]
Hello,

Since this is missing I thought it would be a good idea to have some draft version that can be corrected later of an installation Manual.
One caveat: The following was tested on windows only.
### Aim
At the end of this manual you should be able to run the TIPTOP-EXAMPLE.ipynb notebook down to the third cell of the notebook. 
/!\ After the third the next one require parameter files that are missing.  

### pre-requisit
You need a python installation. For example anaconda has a handy interface to get you that.
Here is a couple of library that are not comprised in the Anaconda base environment that you will need:

- the jupyter-notebook or jupyter lab (depending on your preference, my recommendation : jupyterLab)
- a cuda accelerated GPU, an installation of CUDA and cupy (you'll also need the CUDA toolkit which is installed automatically with cupy if you use anaconda.)
- line_profiler
- sympy

### Installation
Now you need to clone the repository and install the dependencies included in the repository:
Either you open an anaconda terminal with Git installed, navigate to where you want the clone to be and type :
`git clone --recurse-submodules --remote-submodules https://github.com/FabioRossiArcetri/TIPTOP.git`

Or you install git desktop and clone using the URL method.

Then in an Anaconda prompt,
- Navigate to the folder in which you have cloned TIPTOP
- navigate to the folder P3
- install P3 (`pip install -e .` (tested) or `python setup.py install` might work)
- navigate out of P3
- Navigate inside  MASTSEL 
- install MASTSEL:  `pip install -e .`
- Navigate out of MASTSEL
- Navigate inside SEEING
- install SEEING :  `pip install -e .`
- Navigate out of SEEING
- navigate inside of SYMAO
- install SYMAO :  `pip install -e .`

Now you are set to start testing out: 
- open a jupyter notebook or jupyterLab (recommanded) (If you figure out how to do that while being new to jupyter, my hat)
- Open TIPTOP-EXAMPLE.ipynb
- Depending on the version you have there is a couple of things you'll need to change in the parameter file:
- In the second cell, there is a couple of variable initialisation. particularly there is one called `parameterFile`. For me it contain `'HarmoniLTAO_1'`.
- in in the folder perfTest open the file named <your parameterFile name>.ini . (hence for me `HarmoniLTAO_1.ini`)

For peoples unfamiliar with this kind of configuration file, it contains sections that starts with `[sectionname]` and end at the next marker `[sectionName2]` or with the end of file. 

- In the section `[telescope]` (it is the first one for me) you need to change the two path that are in there:
- change after  PathPupil = <your path to your TIPTOP folder>/TIPTOP/P3/aoSystem/data/ELT_CALIBRATION/EELT480pp0.0813spider.fits
- Change after PathStaticOn = '<your path to your TIPTOP folder>/TIPTOP/P3/aoSystem/data/ELT_CALIBRATION/CombinedError_Wavefront_nm.fits'

/!\ For windows users: Some fancypants thinks that python is not clever enough to recognise the odd path slashes of windows path and has introduced the following lines in TIPTOP/P3/aoSystem/aoSystem.py starting line 113:
```python
        # ----- managing paths for Windows OS
        if sys.platform[0:3] == 'win':
            path_pupil     = path_pupil.replace('/','\\')
            path_static_on = path_static_on.replace('/','\\')
            path_static_off= path_static_off.replace('/','\\')
            path_static_pos= path_static_pos.replace('/','\\')
            path_apodizer  = path_apodizer.replace('/','\\')
            path_statModes = path_statModes.replace('/','\\')
```
Unless you are running with python 2.7 or less, comment them they are not needed and they prevent you from running the basic simulation in cell 3.
@FabioRossiArcetri : the problem with this bloc is that in the example notebook at least `path_static_off` is not defined. From what I gather in the available .ini files: `path_static_pos`, `path_apodizer` and `path_statModes` are also not defined. When the path are not  defined, they contain `None` and `.replace` does not know how to deal with non string, and casts an error.

Now the notebook should run smoothly down to the third cell.

**Comment by Teusia** [comment]
We are now at the level of a readthedocs documentation. 
check out: [the documentation](https://tiptop.readthedocs.io)
Please bear in mind this is still under development.

**Comment by saimn** [comment]
@Teusia - Can we close since we have https://tiptop.readthedocs.io/en/main/usage.html#installation ?
