### ISSUE TITLE
TIPTOP-EXAMPLE.py fails for SOUL and SPHERE configurations - LO and PSF jitter issues

### ISSUE THREAD

**Issue by vkooten** [astro-tiptop/TIPTOP#20]
With the update to add in PSF jitter when LO is not enabled, the overallSimulation fails on line 199 in tiptop.py due to the jitter_FWHM referenced before assignment. PSF_jitter needs to be added to the SOUL and SPHERE configuration file for the code to run and the key word needs to be added into the parameterFile.rst along with the correct units and that either LO and PSF_jitter must be declared.

**Comment by guidoagapito** [comment]
jitter_bug branch added and pull request submitted.

**Comment by saimn** [comment]
I think this has been fixed by #21.
