### ISSUE TITLE
readthedocs URL and webhook

### ISSUE THREAD

**Issue by saimn** [astro-tiptop/TIPTOP#26]
Following the migration to https://github.com/astro-tiptop the webhook to trigger builds on readthedocs should be updated. 
However it seems that we have two different URLs:
https://tiptop.readthedocs.io/
https://tiptopdoc.readthedocs.io/ (linked in the README)
We should probably remove the second one and use only the first?

@Teusia - It seems both belong to your RTD account, could you update the webhook (simplest is to delete the existing one and add a new one) and maybe give me, Fabio and Guido, access to the project on readthedocs ? (same username as Github for me, not sure if @FabioRossiArcetri and @guidoagapito have an account ?)

**Comment by Teusia** [comment]
Hello,
Sorry, I forgot about this, 

- I updated the repository address, 
- the tiptopdoc one can be forgotten this was a test on my side, 
- I also added you as maintainer (as well as Guido and Fabio)
Now I need to figure out with the migration to the new adress seems to break the documentation.

**Comment by saimn** [comment]
With #30 the documentation build is now OK, I resynced the webhook and activated PR builds.
Before making the release we can see how to integrate @Teusia's doc updates in #28.
