### ISSUE TITLE
Error when overallSimulation is run with returnRes=True

### ISSUE THREAD

**Issue by laurepiq** [astro-tiptop/TIPTOP#27]
UnboundLocalError: local variable 'results' referenced before assignment (line 257 of tiptop/tiptop.py)

**Comment by laurepiq** [comment]
For me, the error happens with a HARMONI configuration file provided by Benoit.
Another question: could you please clarify what it is returned by the function in case returnRes=True ? Is it exactly same data saved in the FITS file in case of returnRes=False ?

**Comment by guidoagapito** [comment]
When returnRes=True tiptop.py returns HO_res, LO_res (or HO_res if sensor_LO is not set in the parameter file) and it does not save the fits file with the PSFs (it also skips the convolution of HO PSF with LO kernels)

**Comment by guidoagapito** [comment]
I think that this error can be avoided by setting doPlot=False. So, tiptop should refuse to use at the same time returnRes and doPlot.

**Comment by guidoagapito** [comment]
Solved with https://github.com/astro-tiptop/TIPTOP/commit/d89339d07a8ad58c4badec6e986a976bd25312d5
