### ISSUE TITLE
Add PSD to output FITS

### ISSUE THREAD

**Issue by rfetick** [astro-tiptop/TIPTOP#40]
Hello,

It seems important for the Tiptop users (AO scientists and astronomers) to get the PSD as an output of the code. In`tiptop.py` you might want to add the line `hdul1.append(fits.ImageHDU(data=PSD[0:nPointings]))` when you create the FITS file. You might also want to add a header to this FITS extension, at least the frequency step. If the PSD is the 4th extension of the header, then:
`hdr4 = hdul1[4].header`
`hdr4['PIX'] = fao.freq.PSDstep`

Kind regards,

Romain

**Comment by guidoagapito** [comment]
Done, added savePSDs parameter, see https://github.com/astro-tiptop/TIPTOP/commit/6d6cf598496cf02f04df2d6cf460c2e9e07f833b
