### ISSUE TITLE
astropy error

### ISSUE THREAD

**Issue by laurepiq** [astro-tiptop/TIPTOP#45]
Hello,

Running tiptop with the last version 1.2 seems to occur an error. It is astropy.io.fits.cards which returns an error as a FITS keyword is too long. I use astropy version 4.2. The keyword in question has been added by the commit #41.
The bug can be reproduced by running the example given in the Quickstart section of the tiptop documentation:
`overallSimulation("perfTest", "HarmoniSCAO_1", "perfTest", "testPyramid", doPlot=False, doConvolve=False)`

Kind regards,
Laure

**Comment by guidoagapito** [comment]
There is an 80-character limit in the fits header (https://heasarc.gsfc.nasa.gov/docs/heasarc/fits_overview.html) so you cannot add parameter key values that are longer than this.
Unfortunately in the ini file you are using there are keys (in the [telescope] section) that have long strings as their values.
We will look for a way around this problem.

**Comment by guidoagapito** [comment]
Solved with pull request https://github.com/astro-tiptop/TIPTOP/pull/60
